// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/radixdb/v1/radixdb.proto

package radixdbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadixDB_Insert_FullMethodName     = "/radixdb.v1.RadixDB/Insert"
	RadixDB_Get_FullMethodName        = "/radixdb.v1.RadixDB/Get"
	RadixDB_WalkPrefix_FullMethodName = "/radixdb.v1.RadixDB/WalkPrefix"
	RadixDB_Sync_FullMethodName       = "/radixdb.v1.RadixDB/Sync"
	RadixDB_Stats_FullMethodName      = "/radixdb.v1.RadixDB/Stats"
)

// RadixDBClient is the client API for RadixDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RadixDBClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	WalkPrefix(ctx context.Context, in *WalkPrefixRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyRows], error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type radixDBClient struct {
	cc grpc.ClientConnInterface
}

func NewRadixDBClient(cc grpc.ClientConnInterface) RadixDBClient {
	return &radixDBClient{cc}
}

func (c *radixDBClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, RadixDB_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radixDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RadixDB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radixDBClient) WalkPrefix(ctx context.Context, in *WalkPrefixRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyRows], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RadixDB_ServiceDesc.Streams[0], RadixDB_WalkPrefix_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WalkPrefixRequest, KeyRows]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadixDB_WalkPrefixClient = grpc.ServerStreamingClient[KeyRows]

func (c *radixDBClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RadixDB_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radixDBClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, RadixDB_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RadixDBServer is the server API for RadixDB service.
// All implementations must embed UnimplementedRadixDBServer
// for forward compatibility.
type RadixDBServer interface {
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	WalkPrefix(*WalkPrefixRequest, grpc.ServerStreamingServer[KeyRows]) error
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedRadixDBServer()
}

// UnimplementedRadixDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadixDBServer struct{}

func (UnimplementedRadixDBServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedRadixDBServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRadixDBServer) WalkPrefix(*WalkPrefixRequest, grpc.ServerStreamingServer[KeyRows]) error {
	return status.Error(codes.Unimplemented, "method WalkPrefix not implemented")
}
func (UnimplementedRadixDBServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedRadixDBServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedRadixDBServer) mustEmbedUnimplementedRadixDBServer() {}
func (UnimplementedRadixDBServer) testEmbeddedByValue()                 {}

// UnsafeRadixDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadixDBServer will
// result in compilation errors.
type UnsafeRadixDBServer interface {
	mustEmbedUnimplementedRadixDBServer()
}

func RegisterRadixDBServer(s grpc.ServiceRegistrar, srv RadixDBServer) {
	// If the following call panics, it indicates UnimplementedRadixDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadixDB_ServiceDesc, srv)
}

func _RadixDB_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadixDBServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadixDB_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadixDBServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadixDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadixDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadixDB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadixDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadixDB_WalkPrefix_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WalkPrefixRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadixDBServer).WalkPrefix(m, &grpc.GenericServerStream[WalkPrefixRequest, KeyRows]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadixDB_WalkPrefixServer = grpc.ServerStreamingServer[KeyRows]

func _RadixDB_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadixDBServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadixDB_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadixDBServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadixDB_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadixDBServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RadixDB_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadixDBServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RadixDB_ServiceDesc is the grpc.ServiceDesc for RadixDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadixDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radixdb.v1.RadixDB",
	HandlerType: (*RadixDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _RadixDB_Insert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RadixDB_Get_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _RadixDB_Sync_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _RadixDB_Stats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WalkPrefix",
			Handler:       _RadixDB_WalkPrefix_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/radixdb/v1/radixdb.proto",
}
