// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/radixdb/v1/radixdb.proto

package radixdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int32                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	FullPath      string                 `protobuf:"bytes,3,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Row) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Row) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

// Insert: key required (non-empty). id optional — omit for server auto-increment.
// parent_id optional (omit = root, same as 0). full_path is computed server-side.
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id            *int32                 `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ParentId      *int32                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InsertRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *InsertRequest) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type WalkPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkPrefixRequest) Reset() {
	*x = WalkPrefixRequest{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkPrefixRequest) ProtoMessage() {}

func (x *WalkPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkPrefixRequest.ProtoReflect.Descriptor instead.
func (*WalkPrefixRequest) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{5}
}

func (x *WalkPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type KeyRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRows) Reset() {
	*x = KeyRows{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRows) ProtoMessage() {}

func (x *KeyRows) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRows.ProtoReflect.Descriptor instead.
func (*KeyRows) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{6}
}

func (x *KeyRows) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyRows) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{7}
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{8}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{9}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DistinctKeys  uint64                 `protobuf:"varint,1,opt,name=distinct_keys,json=distinctKeys,proto3" json:"distinct_keys,omitempty"`
	TotalRows     uint64                 `protobuf:"varint,2,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_radixdb_v1_radixdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_radixdb_v1_radixdb_proto_rawDescGZIP(), []int{10}
}

func (x *StatsResponse) GetDistinctKeys() uint64 {
	if x != nil {
		return x.DistinctKeys
	}
	return 0
}

func (x *StatsResponse) GetTotalRows() uint64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

var File_proto_radixdb_v1_radixdb_proto protoreflect.FileDescriptor

const file_proto_radixdb_v1_radixdb_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/radixdb/v1/radixdb.proto\x12\n" +
	"radixdb.v1\"O\n" +
	"\x03Row\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x05R\bparentId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\tfull_path\x18\x03 \x01(\tR\bfullPath\"m\n" +
	"\rInsertRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x05H\x00R\x02id\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x05H\x01R\bparentId\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_parent_id\" \n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"H\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12#\n" +
	"\x04rows\x18\x02 \x03(\v2\x0f.radixdb.v1.RowR\x04rows\"+\n" +
	"\x11WalkPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"@\n" +
	"\aKeyRows\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x04rows\x18\x02 \x03(\v2\x0f.radixdb.v1.RowR\x04rows\"\r\n" +
	"\vSyncRequest\"\x0e\n" +
	"\fSyncResponse\"\x0e\n" +
	"\fStatsRequest\"S\n" +
	"\rStatsResponse\x12#\n" +
	"\rdistinct_keys\x18\x01 \x01(\x04R\fdistinctKeys\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x02 \x01(\x04R\ttotalRows2\xbf\x02\n" +
	"\aRadixDB\x12?\n" +
	"\x06Insert\x12\x19.radixdb.v1.InsertRequest\x1a\x1a.radixdb.v1.InsertResponse\x126\n" +
	"\x03Get\x12\x16.radixdb.v1.GetRequest\x1a\x17.radixdb.v1.GetResponse\x12B\n" +
	"\n" +
	"WalkPrefix\x12\x1d.radixdb.v1.WalkPrefixRequest\x1a\x13.radixdb.v1.KeyRows0\x01\x129\n" +
	"\x04Sync\x12\x17.radixdb.v1.SyncRequest\x1a\x18.radixdb.v1.SyncResponse\x12<\n" +
	"\x05Stats\x12\x18.radixdb.v1.StatsRequest\x1a\x19.radixdb.v1.StatsResponseB)Z'artbenchmark/proto/radixdb/v1;radixdbv1b\x06proto3"

var (
	file_proto_radixdb_v1_radixdb_proto_rawDescOnce sync.Once
	file_proto_radixdb_v1_radixdb_proto_rawDescData []byte
)

func file_proto_radixdb_v1_radixdb_proto_rawDescGZIP() []byte {
	file_proto_radixdb_v1_radixdb_proto_rawDescOnce.Do(func() {
		file_proto_radixdb_v1_radixdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_radixdb_v1_radixdb_proto_rawDesc), len(file_proto_radixdb_v1_radixdb_proto_rawDesc)))
	})
	return file_proto_radixdb_v1_radixdb_proto_rawDescData
}

var file_proto_radixdb_v1_radixdb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_radixdb_v1_radixdb_proto_goTypes = []any{
	(*Row)(nil),               // 0: radixdb.v1.Row
	(*InsertRequest)(nil),     // 1: radixdb.v1.InsertRequest
	(*InsertResponse)(nil),    // 2: radixdb.v1.InsertResponse
	(*GetRequest)(nil),        // 3: radixdb.v1.GetRequest
	(*GetResponse)(nil),       // 4: radixdb.v1.GetResponse
	(*WalkPrefixRequest)(nil), // 5: radixdb.v1.WalkPrefixRequest
	(*KeyRows)(nil),           // 6: radixdb.v1.KeyRows
	(*SyncRequest)(nil),       // 7: radixdb.v1.SyncRequest
	(*SyncResponse)(nil),      // 8: radixdb.v1.SyncResponse
	(*StatsRequest)(nil),      // 9: radixdb.v1.StatsRequest
	(*StatsResponse)(nil),     // 10: radixdb.v1.StatsResponse
}
var file_proto_radixdb_v1_radixdb_proto_depIdxs = []int32{
	0,  // 0: radixdb.v1.GetResponse.rows:type_name -> radixdb.v1.Row
	0,  // 1: radixdb.v1.KeyRows.rows:type_name -> radixdb.v1.Row
	1,  // 2: radixdb.v1.RadixDB.Insert:input_type -> radixdb.v1.InsertRequest
	3,  // 3: radixdb.v1.RadixDB.Get:input_type -> radixdb.v1.GetRequest
	5,  // 4: radixdb.v1.RadixDB.WalkPrefix:input_type -> radixdb.v1.WalkPrefixRequest
	7,  // 5: radixdb.v1.RadixDB.Sync:input_type -> radixdb.v1.SyncRequest
	9,  // 6: radixdb.v1.RadixDB.Stats:input_type -> radixdb.v1.StatsRequest
	2,  // 7: radixdb.v1.RadixDB.Insert:output_type -> radixdb.v1.InsertResponse
	4,  // 8: radixdb.v1.RadixDB.Get:output_type -> radixdb.v1.GetResponse
	6,  // 9: radixdb.v1.RadixDB.WalkPrefix:output_type -> radixdb.v1.KeyRows
	8,  // 10: radixdb.v1.RadixDB.Sync:output_type -> radixdb.v1.SyncResponse
	10, // 11: radixdb.v1.RadixDB.Stats:output_type -> radixdb.v1.StatsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_radixdb_v1_radixdb_proto_init() }
func file_proto_radixdb_v1_radixdb_proto_init() {
	if File_proto_radixdb_v1_radixdb_proto != nil {
		return
	}
	file_proto_radixdb_v1_radixdb_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_radixdb_v1_radixdb_proto_rawDesc), len(file_proto_radixdb_v1_radixdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_radixdb_v1_radixdb_proto_goTypes,
		DependencyIndexes: file_proto_radixdb_v1_radixdb_proto_depIdxs,
		MessageInfos:      file_proto_radixdb_v1_radixdb_proto_msgTypes,
	}.Build()
	File_proto_radixdb_v1_radixdb_proto = out.File
	file_proto_radixdb_v1_radixdb_proto_goTypes = nil
	file_proto_radixdb_v1_radixdb_proto_depIdxs = nil
}
